project:
  type: website
  output-dir: docs

website:
  title: "Mutual Blog"
  navbar:
    right:
      - text: Posts
        href: posts/index.qmd
      - about.qmd
      - text: Currículo
        href: curriculo.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

lang: pt
  

  