project:
  type: website
  output-dir: docs

website:
  title: "Mutual Blog"
  site-url: "https://lemuelemos.github.io/blog_mutual-1"
  description: "Blog sobre análise de dados, modelagem quantitativa e programação em R aplicados ao mercado financeiro."
  navbar:
    right:
      - text: Posts
        href: posts/index.qmd
      - about.qmd
      - text: Currículo
        href: curriculo.qmd
      - icon: github
        href: https://github.com/lemuelemos
      - icon: twitter
        href: https://twitter.com/lemuelemos

format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

lang: pt
