---
title: "Sobre Mim"
image: 'https://avatars.githubusercontent.com/u/17839354?v=4'
about:
  template: jolla
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com
    - icon: linkedin
      text: LinkedIn
      href: https://linkedin.com
    - icon: github
      text: Github
      href: https://github.com
---

Me chamo Lemuel e nos últimos 10 anos venho me dedicando à programação e à análise de dados. Sou formado em economia, com mestrado em economia e doutorado na área de finanças, todos pela UFRN. Atualmente, trabalho como analista de dados na área de finanças e sou apaixonado por programação e análise de dados. Ultimamente, dediquei uma boa parte do meu tempo estudando e trabalhando com Python e R na área de fundos de investimentos. Trabalho em um escritório de investimentos e sou responsável por toda a parte de análise de dados e programação, onde desenvolvo relatórios e dashboards de acompanhamento dos resultados da empresa.


Na área acadêmica, dediquei-me bastante ao aprendizado de programação, sempre voltado para a utilização de ferramentas de pesquisa quantitativa. Já executei modelos que vão desde simples regressões até modelos de volatilidade com GARCH e DCC-GARCH, além de modelos de séries temporais, que variam desde os modelos clássicos de séries temporais (ARIMA's) até modelos multivariados como VAR e VEC. Atualmente, meu foco está na pesquisa do comportamento dos fundos de investimento, onde analisei o comportamento do investidor frente às mudanças das variáveis macroeconômicas e o testei para análise da existência de gerenciamento de resultados por parte dos gestores, em relação à captura da taxa de performance. Recentemente, utilizei modelos de dados em painel e testes não paramétricos para diferença de médias. 

Durante o doutorado, comecei a trabalhar em um escritório de assessoria de investimentos, onde participei de todas as áreas, desde a mesa de operações de renda variável até a área de análise de dados e BI da empresa. Um ponto que merece destaque é que, além da área de análise de dados, desenvolvi diversos robôs para automação de rotinas administrativas e operacionais. Um dos grandes projetos que liderei na empresa foi a criação de um sistema de cálculo de comissões, o que representa um desafio significativo para empresas de assessorias. Esse sistema foi projetado com a personalização de diversas regras de negócio, proporcionando uma elevada flexibilidade e confiança nos processos de comissão. Anteriormente, todo o processo era realizado através de planilhas de Excel, o que era bastante trabalhoso e demorado. A implementação desse sistema nos permitiu economizar várias horas de trabalho.

Além disso, nosso outro grande projeto foi montar um dashboard que permite o acompanhamento diário da produção da mesa de operações e dos assessores. Esse dashboard possibilita a integração de diversos relatórios em bases de dados unificadas. Ele é desenvolvido utilizando as tecnologias Node/React e conta com uma API no backend em R/Python. Tenho como objetivo para os próximos meses integrar novas ferramentas de IA, como os modelos LLM, para fornecer uma interface mais interativa aos usuários, além dos dados apresentados via dashboards. 

Com base em toda essa experiência e aprendizado, decidi criar este blog para compartilhar conhecimento e insights. Aqui, vamos nos concentrar na criação de dashboards em R Shiny e Dash Plotly, na análise de dados da indústria de fundos e na modelagem de métricas de acompanhamento, especialmente relacionadas à indústria de fundos de investimento.

Seja bem-vindo ao meu blog e espero que as informações compartilhadas aqui possam ser úteis para você, assim como têm sido para mim ao longo desses anos. 










